# Generated by Django 5.0.6 on 2025-08-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notificationlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("STARTED", "Started"),
                    ("SENT", "Sent"),
                    ("FAILED", "Failed"),
                    ("RETRYING", "Retrying"),
                    ("CANCELED", "Canceled"),
                ],
                default="Started",
                max_length=10,
            ),
        ),
    ]
